// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upjehnxykpicwdnhtyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwamVobnh5a3BpY3dkbmh0eXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTAyNTYsImV4cCI6MjA2MTY2NjI1Nn0.6ryRGlf00ChkHYx6X7959tsohl6tBJ6BUtM9kC4EB7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});